micronaut:
  server:
    cors:
      enabled: true
auth:
  oauth:
    jwks-url: https://auth.kodality.dev/realms/terminology/protocol/openid-connect/certs

termx:
  web-url: http://localhost:4200


github:
  client:
    id: 'Iv1.b0be484dcc3c28ae'
    secret: 'bffd5a32dcf31667974c09c429f690f057d4182f'
  app-name: termx-dev-local-publisher
